version: "3.8"
services:
  recorder:
    build:
      context: .
      dockerfile: Dockerfile.recording
    container_name: meetng_bot
    command: >
      python3 meetbot.py
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    tty: true
